# Generated by Django 4.0.2 on 2023-05-09 01:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0002_alter_customuser_options_alter_customuser_managers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('question_type', models.CharField(choices=[('true-false', 'True/False'), ('multiple-choice', 'Multiple Choice'), ('check-all', 'Check All That Apply'), ('free-form', 'Free-form Answers')], max_length=20)),
                ('choices', models.TextField(blank=True, null=True)),
                ('correct_answers', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('time_limit', models.PositiveIntegerField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_quizzes', to=settings.AUTH_USER_MODEL)),
                ('questions', models.ManyToManyField(to='quiz_app.Question')),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='quizzes',
            field=models.ManyToManyField(blank=True, related_name='quiz_creators', to='quiz_app.Quiz'),
        ),
    ]
