runtime: python39
entrypoint: gunicorn -b :$PORT prelim.wsgi

env_variables:
  DJANGO_SETTINGS_MODULE: "prelim.settings"

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10
